/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.arbol;

import clases.Ganadores;
import clases.Participante;
import clases.Participantes;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.Collections;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import ventanas.Inicio;

/**
 *
 * @author MINEDUCYT
 */
public class EnArbol16 extends javax.swing.JFrame {

    DefaultTableModel participantes;
    Ganadores ganador = new Ganadores();

    public EnArbol16() {
        initComponents();
        this.setLocationRelativeTo(null);

        participantes = new DefaultTableModel();
        participantes.addColumn("Participante");
        TableParticipantes.setModel(participantes);
        
              Font font = new Font("Arial Black", Font.PLAIN, 12);
        TableParticipantes.setFont(font);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setForeground(new Color(255, 255, 255));
        renderer.setBackground(new Color(51, 51, 51));
        renderer.setFont(font);
        TableParticipantes.setDefaultRenderer(Object.class, renderer);
        TableParticipantes.setEnabled(false);
        TableParticipantes.setShowGrid(false);
        TableParticipantes.setDefaultEditor(Object.class, null);
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);

        ImageIcon wallpaper = new ImageIcon("src/img/Wallpaper2.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        LabelWallpaper.setIcon(icon);

        CuartosFinal.setVisible(false);
        SemiFinal.setVisible(false);
        Final.setVisible(false);
        cargarParticipantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TableParticipantes = new javax.swing.JTable();
        Nombre1 = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JTextField();
        Nombre3 = new javax.swing.JTextField();
        Nombre4 = new javax.swing.JTextField();
        Nombre5 = new javax.swing.JTextField();
        Nombre6 = new javax.swing.JTextField();
        Nombre7 = new javax.swing.JTextField();
        Nombre8 = new javax.swing.JTextField();
        Nombre9 = new javax.swing.JTextField();
        Nombre10 = new javax.swing.JTextField();
        Nombre11 = new javax.swing.JTextField();
        Nombre12 = new javax.swing.JTextField();
        Nombre13 = new javax.swing.JTextField();
        Nombre14 = new javax.swing.JTextField();
        Nombre15 = new javax.swing.JTextField();
        Nombre16 = new javax.swing.JTextField();
        Nombre17 = new javax.swing.JTextField();
        Nombre18 = new javax.swing.JTextField();
        Nombre19 = new javax.swing.JTextField();
        Nombre20 = new javax.swing.JTextField();
        Nombre21 = new javax.swing.JTextField();
        Nombre22 = new javax.swing.JTextField();
        Nombre23 = new javax.swing.JTextField();
        Nombre24 = new javax.swing.JTextField();
        Nombre25 = new javax.swing.JTextField();
        Nombre26 = new javax.swing.JTextField();
        Nombre27 = new javax.swing.JTextField();
        Nombre28 = new javax.swing.JTextField();
        Nombre29 = new javax.swing.JTextField();
        Nombre30 = new javax.swing.JTextField();
        Punto1 = new javax.swing.JTextField();
        Punto2 = new javax.swing.JTextField();
        Punto3 = new javax.swing.JTextField();
        Punto4 = new javax.swing.JTextField();
        Punto5 = new javax.swing.JTextField();
        Punto6 = new javax.swing.JTextField();
        Punto7 = new javax.swing.JTextField();
        Punto8 = new javax.swing.JTextField();
        Punto9 = new javax.swing.JTextField();
        Punto10 = new javax.swing.JTextField();
        Punto11 = new javax.swing.JTextField();
        Punto12 = new javax.swing.JTextField();
        Punto13 = new javax.swing.JTextField();
        Punto14 = new javax.swing.JTextField();
        Punto15 = new javax.swing.JTextField();
        Punto16 = new javax.swing.JTextField();
        Punto17 = new javax.swing.JTextField();
        Punto18 = new javax.swing.JTextField();
        Punto19 = new javax.swing.JTextField();
        Punto20 = new javax.swing.JTextField();
        Punto21 = new javax.swing.JTextField();
        Punto22 = new javax.swing.JTextField();
        Punto24 = new javax.swing.JTextField();
        Punto23 = new javax.swing.JTextField();
        Punto25 = new javax.swing.JTextField();
        Punto26 = new javax.swing.JTextField();
        Punto27 = new javax.swing.JTextField();
        Punto28 = new javax.swing.JTextField();
        Punto29 = new javax.swing.JTextField();
        Punto30 = new javax.swing.JTextField();
        Ganador = new javax.swing.JTextField();
        GanadorPunto = new javax.swing.JTextField();
        Ronda1 = new javax.swing.JButton();
        CuartosFinal = new javax.swing.JButton();
        SemiFinal = new javax.swing.JButton();
        Final = new javax.swing.JButton();
        Reset1 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TableParticipantes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 290));

        Nombre1.setEditable(false);
        Nombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 90, 30));

        Nombre2.setEditable(false);
        Nombre2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, 30));

        Nombre3.setEditable(false);
        Nombre3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 90, 30));

        Nombre4.setEditable(false);
        Nombre4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 90, 30));

        Nombre5.setEditable(false);
        Nombre5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 90, 30));

        Nombre6.setEditable(false);
        Nombre6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 90, 30));

        Nombre7.setEditable(false);
        Nombre7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 90, 30));

        Nombre8.setEditable(false);
        Nombre8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 90, 30));

        Nombre9.setEditable(false);
        Nombre9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 90, 30));

        Nombre10.setEditable(false);
        Nombre10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 130, 90, 30));

        Nombre11.setEditable(false);
        Nombre11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 180, 90, 30));

        Nombre12.setEditable(false);
        Nombre12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 210, 90, 30));

        Nombre13.setEditable(false);
        Nombre13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 270, 90, 30));

        Nombre14.setEditable(false);
        Nombre14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 300, 90, 30));

        Nombre15.setEditable(false);
        Nombre15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 350, 90, 30));

        Nombre16.setEditable(false);
        Nombre16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 380, 90, 30));

        Nombre17.setEditable(false);
        Nombre17.setBackground(new java.awt.Color(56, 56, 56));
        Nombre17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre17.setForeground(new java.awt.Color(0, 0, 0));
        Nombre17.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 90, 30));

        Nombre18.setEditable(false);
        Nombre18.setBackground(new java.awt.Color(56, 56, 56));
        Nombre18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre18.setForeground(new java.awt.Color(0, 0, 0));
        Nombre18.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 90, 30));

        Nombre19.setEditable(false);
        Nombre19.setBackground(new java.awt.Color(56, 56, 56));
        Nombre19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre19.setForeground(new java.awt.Color(0, 0, 0));
        Nombre19.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 90, 30));

        Nombre20.setEditable(false);
        Nombre20.setBackground(new java.awt.Color(56, 56, 56));
        Nombre20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre20.setForeground(new java.awt.Color(0, 0, 0));
        Nombre20.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 90, 30));

        Nombre21.setEditable(false);
        Nombre21.setBackground(new java.awt.Color(56, 56, 56));
        Nombre21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre21.setForeground(new java.awt.Color(0, 0, 0));
        Nombre21.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 180, 90, 30));

        Nombre22.setEditable(false);
        Nombre22.setBackground(new java.awt.Color(56, 56, 56));
        Nombre22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre22.setForeground(new java.awt.Color(0, 0, 0));
        Nombre22.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, 90, 30));

        Nombre23.setEditable(false);
        Nombre23.setBackground(new java.awt.Color(56, 56, 56));
        Nombre23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre23.setForeground(new java.awt.Color(0, 0, 0));
        Nombre23.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 270, 90, 30));

        Nombre24.setEditable(false);
        Nombre24.setBackground(new java.awt.Color(56, 56, 56));
        Nombre24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre24.setForeground(new java.awt.Color(0, 0, 0));
        Nombre24.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 300, 90, 30));

        Nombre25.setEditable(false);
        Nombre25.setBackground(new java.awt.Color(56, 56, 56));
        Nombre25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre25.setForeground(new java.awt.Color(0, 0, 0));
        Nombre25.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 90, 30));

        Nombre26.setEditable(false);
        Nombre26.setBackground(new java.awt.Color(56, 56, 56));
        Nombre26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre26.setForeground(new java.awt.Color(0, 0, 0));
        Nombre26.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 90, 30));

        Nombre27.setEditable(false);
        Nombre27.setBackground(new java.awt.Color(56, 56, 56));
        Nombre27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre27.setForeground(new java.awt.Color(0, 0, 0));
        Nombre27.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre27, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 90, 30));

        Nombre28.setEditable(false);
        Nombre28.setBackground(new java.awt.Color(56, 56, 56));
        Nombre28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre28.setForeground(new java.awt.Color(0, 0, 0));
        Nombre28.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre28, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 90, 30));

        Nombre29.setEditable(false);
        Nombre29.setBackground(new java.awt.Color(56, 56, 56));
        Nombre29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre29.setForeground(new java.awt.Color(0, 0, 0));
        Nombre29.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre29, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 90, 30));

        Nombre30.setEditable(false);
        Nombre30.setBackground(new java.awt.Color(56, 56, 56));
        Nombre30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre30.setForeground(new java.awt.Color(0, 0, 0));
        Nombre30.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre30, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 90, 30));

        Punto1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 30, 30));

        Punto2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 30, 30));

        Punto3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 30, 30));

        Punto4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 30, 30));

        Punto5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 30, 30));

        Punto6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 30, 30));

        Punto7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 30, 30));

        Punto8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 30, 30));

        Punto9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 100, 30, 30));

        Punto10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 130, 30, 30));

        Punto11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 180, 30, 30));

        Punto12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 210, 30, 30));

        Punto13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 270, 30, 30));

        Punto14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 300, 30, 30));

        Punto15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 350, 30, 30));

        Punto16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 380, 30, 30));

        Punto17.setEditable(false);
        Punto17.setBackground(new java.awt.Color(56, 56, 56));
        Punto17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto17.setForeground(new java.awt.Color(0, 0, 0));
        Punto17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 30, 30));

        Punto18.setEditable(false);
        Punto18.setBackground(new java.awt.Color(56, 56, 56));
        Punto18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto18.setForeground(new java.awt.Color(0, 0, 0));
        Punto18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 30, 30));

        Punto19.setEditable(false);
        Punto19.setBackground(new java.awt.Color(56, 56, 56));
        Punto19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto19.setForeground(new java.awt.Color(0, 0, 0));
        Punto19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 30, 30));

        Punto20.setEditable(false);
        Punto20.setBackground(new java.awt.Color(56, 56, 56));
        Punto20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto20.setForeground(new java.awt.Color(0, 0, 0));
        Punto20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 30, 30));

        Punto21.setEditable(false);
        Punto21.setBackground(new java.awt.Color(56, 56, 56));
        Punto21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto21.setForeground(new java.awt.Color(0, 0, 0));
        Punto21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 30, 30));

        Punto22.setEditable(false);
        Punto22.setBackground(new java.awt.Color(56, 56, 56));
        Punto22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto22.setForeground(new java.awt.Color(0, 0, 0));
        Punto22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 210, 30, 30));

        Punto24.setEditable(false);
        Punto24.setBackground(new java.awt.Color(56, 56, 56));
        Punto24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto24.setForeground(new java.awt.Color(0, 0, 0));
        Punto24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, 30, 30));

        Punto23.setEditable(false);
        Punto23.setBackground(new java.awt.Color(56, 56, 56));
        Punto23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto23.setForeground(new java.awt.Color(0, 0, 0));
        Punto23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, 30, 30));

        Punto25.setEditable(false);
        Punto25.setBackground(new java.awt.Color(56, 56, 56));
        Punto25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto25.setForeground(new java.awt.Color(0, 0, 0));
        Punto25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto25, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 30, 30));

        Punto26.setEditable(false);
        Punto26.setBackground(new java.awt.Color(56, 56, 56));
        Punto26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto26.setForeground(new java.awt.Color(0, 0, 0));
        Punto26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 30, 30));

        Punto27.setEditable(false);
        Punto27.setBackground(new java.awt.Color(56, 56, 56));
        Punto27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto27.setForeground(new java.awt.Color(0, 0, 0));
        Punto27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto27, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, 30, 30));

        Punto28.setEditable(false);
        Punto28.setBackground(new java.awt.Color(56, 56, 56));
        Punto28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto28.setForeground(new java.awt.Color(0, 0, 0));
        Punto28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto28, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, 30, 30));

        Punto29.setEditable(false);
        Punto29.setBackground(new java.awt.Color(56, 56, 56));
        Punto29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto29.setForeground(new java.awt.Color(0, 0, 0));
        Punto29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto29, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 30, 30));

        Punto30.setEditable(false);
        Punto30.setBackground(new java.awt.Color(56, 56, 56));
        Punto30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto30.setForeground(new java.awt.Color(0, 0, 0));
        Punto30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto30, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 30, 30));

        Ganador.setEditable(false);
        Ganador.setBackground(new java.awt.Color(56, 56, 56));
        Ganador.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Ganador.setForeground(new java.awt.Color(255, 255, 255));
        Ganador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ganador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 260, 60));

        GanadorPunto.setEditable(false);
        GanadorPunto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        GanadorPunto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(GanadorPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 30, 30));

        Ronda1.setBackground(new java.awt.Color(56, 56, 56));
        Ronda1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Ronda1.setForeground(new java.awt.Color(255, 255, 255));
        Ronda1.setText("Ronda1");
        Ronda1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ronda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ronda1ActionPerformed(evt);
            }
        });
        getContentPane().add(Ronda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 260, 60));

        CuartosFinal.setBackground(new java.awt.Color(56, 56, 56));
        CuartosFinal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CuartosFinal.setForeground(new java.awt.Color(255, 255, 255));
        CuartosFinal.setText("Cuartos de Final");
        CuartosFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CuartosFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuartosFinalActionPerformed(evt);
            }
        });
        getContentPane().add(CuartosFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 260, 60));

        SemiFinal.setBackground(new java.awt.Color(56, 56, 56));
        SemiFinal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SemiFinal.setForeground(new java.awt.Color(255, 255, 255));
        SemiFinal.setText("SemiFinal");
        SemiFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SemiFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemiFinalActionPerformed(evt);
            }
        });
        getContentPane().add(SemiFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 260, 60));

        Final.setBackground(new java.awt.Color(56, 56, 56));
        Final.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Final.setForeground(new java.awt.Color(255, 255, 255));
        Final.setText("Final");
        Final.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalActionPerformed(evt);
            }
        });
        getContentPane().add(Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 260, 60));

        Reset1.setBackground(new java.awt.Color(56, 56, 56));
        Reset1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Reset1.setForeground(new java.awt.Color(255, 255, 255));
        Reset1.setText("Otro Torneo");
        Reset1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(Reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 130, 60));

        Reset.setBackground(new java.awt.Color(56, 56, 56));
        Reset.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Nuevo");
        Reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 130, 60));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CuartosFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuartosFinalActionPerformed

        JTextField[] nombres = {Nombre17, Nombre18, Nombre19, Nombre20, Nombre21, Nombre22, Nombre23, Nombre24};
        JTextField[] puntos = {Punto17, Punto18, Punto19, Punto20, Punto21, Punto22, Punto23, Punto24};
        JTextField[] resultadoNombres = {Nombre25, Nombre26, Nombre27, Nombre28};
        JTextField[] resultadoPuntos = {Punto25, Punto26, Punto27, Punto28};

        String Resultado = ganador.Calculos(nombres, puntos, resultadoNombres, resultadoPuntos);

       

        if (Resultado.equals("")) {
            JOptionPane.showMessageDialog(null, "Felicidades a los participantes por pasar a la Sem iFinal");
            CuartosFinal.setVisible(false);
            SemiFinal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, Resultado);
        }

    }//GEN-LAST:event_CuartosFinalActionPerformed

    private void SemiFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemiFinalActionPerformed

        JTextField[] nombres = {Nombre25, Nombre26, Nombre27, Nombre28};
        JTextField[] puntos = {Punto25, Punto26, Punto27, Punto28};
        JTextField[] resultadoNombres = {Nombre29, Nombre30};
        JTextField[] resultadoPuntos = {Punto29, Punto30};

        String Resultado = ganador.Calculos(nombres, puntos, resultadoNombres, resultadoPuntos);

       

        if (Resultado.equals("")) {
            JOptionPane.showMessageDialog(null, "Bienvenidos a la final, que sera entre los participantes\n" + Nombre29.getText() + " VS " + Nombre30.getText());
            SemiFinal.setVisible(false);
            Final.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, Resultado);
        }
    }//GEN-LAST:event_SemiFinalActionPerformed

    private void FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalActionPerformed

        JTextField[] nombres = {Nombre29, Nombre30};
        JTextField[] puntos = {Punto29, Punto30};
        JTextField[] resultadoNombres = {Ganador};
        JTextField[] resultadoPuntos = {GanadorPunto};

        String Resultado = ganador.Calculos(nombres, puntos, resultadoNombres, resultadoPuntos);

       

        Ganador.setBackground(new Color(56, 56, 56));
        
        if (Resultado.equals("")) {
            JOptionPane.showMessageDialog(null, "Felicidades a Gandor del Torneo " + Ganador.getText());
            Final.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, Resultado);
        }

    }//GEN-LAST:event_FinalActionPerformed

    private void Ronda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ronda1ActionPerformed

        JTextField[] nombres = {Nombre1, Nombre2, Nombre3, Nombre4, Nombre5, Nombre6, Nombre7, Nombre8, Nombre9, Nombre10, Nombre11, Nombre12, Nombre13, Nombre14, Nombre15, Nombre16};
        JTextField[] puntos = {Punto1, Punto2, Punto3, Punto4, Punto5, Punto6, Punto7, Punto8, Punto9, Punto10, Punto11, Punto12, Punto13, Punto14, Punto15, Punto16};
        JTextField[] resultadoNombres = {Nombre17, Nombre18, Nombre19, Nombre20, Nombre21, Nombre22, Nombre23, Nombre24};
        JTextField[] resultadoPuntos = {Punto17, Punto18, Punto19, Punto20, Punto21, Punto22, Punto23, Punto24};

        String Resultado = ganador.Calculos(nombres, puntos, resultadoNombres, resultadoPuntos);

       

        if (Resultado.equals("")) {
            JOptionPane.showMessageDialog(null, "Felicidades a los participantes por pasar a los Cuartos de Final");
            Ronda1.setVisible(false);
            CuartosFinal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, Resultado);
        }

    }//GEN-LAST:event_Ronda1ActionPerformed

    private void Reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset1ActionPerformed
        new EnArbol16().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Reset1ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ResetActionPerformed

    private void cargarParticipantes() {
        int x = 1;
        List<Participante> data = Participantes.getParticipantes();
        for (Participante p : data) {
            participantes.addRow(new Object[]{p.getNombre()});
        }
        Collections.shuffle(data);

        for (Participante p : data) {
            switch (x) {
                case 1 ->
                    Nombre1.setText(p.getNombre());
                case 2 ->
                    Nombre2.setText(p.getNombre());
                case 3 ->
                    Nombre3.setText(p.getNombre());
                case 4 ->
                    Nombre4.setText(p.getNombre());
                case 5 ->
                    Nombre5.setText(p.getNombre());
                case 6 ->
                    Nombre6.setText(p.getNombre());
                case 7 ->
                    Nombre7.setText(p.getNombre());
                case 8 ->
                    Nombre8.setText(p.getNombre());
                case 9 ->
                    Nombre9.setText(p.getNombre());
                case 10 ->
                    Nombre10.setText(p.getNombre());
                case 11 ->
                    Nombre11.setText(p.getNombre());
                case 12 ->
                    Nombre12.setText(p.getNombre());
                case 13 ->
                    Nombre13.setText(p.getNombre());
                case 14 ->
                    Nombre14.setText(p.getNombre());
                case 15 ->
                    Nombre15.setText(p.getNombre());
                case 16 ->
                    Nombre16.setText(p.getNombre());
                default -> {
                }
            }

            x++;
        }
        if (Nombre16.getText().isEmpty()) {
            Nombre16.setText("(No hay)");
            Punto15.setEditable(false);
            Punto16.setEditable(false);
            Punto15.setText("0");
            Punto16.setText("0");
            participantes.addRow(new Object[]{"(No hay)"});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnArbol16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnArbol16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnArbol16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnArbol16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnArbol16().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CuartosFinal;
    private javax.swing.JButton Final;
    private javax.swing.JTextField Ganador;
    private javax.swing.JTextField GanadorPunto;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JTextField Nombre10;
    private javax.swing.JTextField Nombre11;
    private javax.swing.JTextField Nombre12;
    private javax.swing.JTextField Nombre13;
    private javax.swing.JTextField Nombre14;
    private javax.swing.JTextField Nombre15;
    private javax.swing.JTextField Nombre16;
    private javax.swing.JTextField Nombre17;
    private javax.swing.JTextField Nombre18;
    private javax.swing.JTextField Nombre19;
    private javax.swing.JTextField Nombre2;
    private javax.swing.JTextField Nombre20;
    private javax.swing.JTextField Nombre21;
    private javax.swing.JTextField Nombre22;
    private javax.swing.JTextField Nombre23;
    private javax.swing.JTextField Nombre24;
    private javax.swing.JTextField Nombre25;
    private javax.swing.JTextField Nombre26;
    private javax.swing.JTextField Nombre27;
    private javax.swing.JTextField Nombre28;
    private javax.swing.JTextField Nombre29;
    private javax.swing.JTextField Nombre3;
    private javax.swing.JTextField Nombre30;
    private javax.swing.JTextField Nombre4;
    private javax.swing.JTextField Nombre5;
    private javax.swing.JTextField Nombre6;
    private javax.swing.JTextField Nombre7;
    private javax.swing.JTextField Nombre8;
    private javax.swing.JTextField Nombre9;
    private javax.swing.JTextField Punto1;
    private javax.swing.JTextField Punto10;
    private javax.swing.JTextField Punto11;
    private javax.swing.JTextField Punto12;
    private javax.swing.JTextField Punto13;
    private javax.swing.JTextField Punto14;
    private javax.swing.JTextField Punto15;
    private javax.swing.JTextField Punto16;
    private javax.swing.JTextField Punto17;
    private javax.swing.JTextField Punto18;
    private javax.swing.JTextField Punto19;
    private javax.swing.JTextField Punto2;
    private javax.swing.JTextField Punto20;
    private javax.swing.JTextField Punto21;
    private javax.swing.JTextField Punto22;
    private javax.swing.JTextField Punto23;
    private javax.swing.JTextField Punto24;
    private javax.swing.JTextField Punto25;
    private javax.swing.JTextField Punto26;
    private javax.swing.JTextField Punto27;
    private javax.swing.JTextField Punto28;
    private javax.swing.JTextField Punto29;
    private javax.swing.JTextField Punto3;
    private javax.swing.JTextField Punto30;
    private javax.swing.JTextField Punto4;
    private javax.swing.JTextField Punto5;
    private javax.swing.JTextField Punto6;
    private javax.swing.JTextField Punto7;
    private javax.swing.JTextField Punto8;
    private javax.swing.JTextField Punto9;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Reset1;
    private javax.swing.JButton Ronda1;
    private javax.swing.JButton SemiFinal;
    private javax.swing.JTable TableParticipantes;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
