/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.arbol;

import clases.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.Collections;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import ventanas.Inicio;

/**
 *
 * @author MINEDUCYT
 */
public class EnArbol10 extends javax.swing.JFrame {

    DefaultTableModel participantes;
    Ganadores ganador = new Ganadores();

    public EnArbol10() {
        initComponents();
        this.setLocationRelativeTo(null);

        participantes = new DefaultTableModel();
        participantes.addColumn("Participante");
        TableParticipantes.setModel(participantes);

        Font font = new Font("Arial Black", Font.PLAIN, 12);
        TableParticipantes.setFont(font);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setForeground(new Color(255, 255, 255));
        renderer.setBackground(new Color(51, 51, 51));
        renderer.setFont(font);
        TableParticipantes.setDefaultRenderer(Object.class, renderer);
        TableParticipantes.setEnabled(false);
        TableParticipantes.setShowGrid(false);
        TableParticipantes.setDefaultEditor(Object.class, null);
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);

        ImageIcon wallpaper = new ImageIcon("src/img/Wallpaper2.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        LabelWallpaper.setIcon(icon);

        CuartosFinal.setVisible(false);
        SemiFinal.setVisible(false);
        Final.setVisible(false);
        cargarParticipantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TableParticipantes = new javax.swing.JTable();
        Nombre1 = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JTextField();
        Nombre3 = new javax.swing.JTextField();
        Nombre4 = new javax.swing.JTextField();
        Nombre5 = new javax.swing.JTextField();
        Nombre6 = new javax.swing.JTextField();
        Nombre7 = new javax.swing.JTextField();
        Nombre8 = new javax.swing.JTextField();
        Nombre9 = new javax.swing.JTextField();
        Nombre10 = new javax.swing.JTextField();
        Nombre11 = new javax.swing.JTextField();
        Nombre12 = new javax.swing.JTextField();
        Nombre13 = new javax.swing.JTextField();
        Nombre14 = new javax.swing.JTextField();
        Nombre15 = new javax.swing.JTextField();
        Nombre16 = new javax.swing.JTextField();
        Nombre17 = new javax.swing.JTextField();
        Nombre18 = new javax.swing.JTextField();
        Nombre19 = new javax.swing.JTextField();
        Nombre20 = new javax.swing.JTextField();
        Punto3 = new javax.swing.JTextField();
        Punto4 = new javax.swing.JTextField();
        Punto5 = new javax.swing.JTextField();
        Punto6 = new javax.swing.JTextField();
        Punto7 = new javax.swing.JTextField();
        Punto8 = new javax.swing.JTextField();
        Punto9 = new javax.swing.JTextField();
        Punto10 = new javax.swing.JTextField();
        Punto11 = new javax.swing.JTextField();
        Punto12 = new javax.swing.JTextField();
        Punto13 = new javax.swing.JTextField();
        Punto14 = new javax.swing.JTextField();
        Punto15 = new javax.swing.JTextField();
        Punto16 = new javax.swing.JTextField();
        Punto17 = new javax.swing.JTextField();
        Punto18 = new javax.swing.JTextField();
        Punto19 = new javax.swing.JTextField();
        Punto20 = new javax.swing.JTextField();
        Ganador = new javax.swing.JTextField();
        GanadorPunto = new javax.swing.JTextField();
        Ronda1 = new javax.swing.JButton();
        CuartosFinal = new javax.swing.JButton();
        SemiFinal = new javax.swing.JButton();
        Final = new javax.swing.JButton();
        Reset1 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TableParticipantes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 190));

        Nombre1.setEditable(false);
        Nombre1.setBackground(new java.awt.Color(56, 56, 56));
        Nombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        Nombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombre1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 120, 30));

        Nombre2.setEditable(false);
        Nombre2.setBackground(new java.awt.Color(56, 56, 56));
        Nombre2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        Nombre2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombre2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, 120, 30));

        Nombre3.setEditable(false);
        Nombre3.setBackground(new java.awt.Color(255, 255, 255));
        Nombre3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre3.setForeground(new java.awt.Color(0, 0, 0));
        Nombre3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 90, 30));

        Nombre4.setEditable(false);
        Nombre4.setBackground(new java.awt.Color(255, 255, 255));
        Nombre4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre4.setForeground(new java.awt.Color(0, 0, 0));
        Nombre4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 90, 30));

        Nombre5.setEditable(false);
        Nombre5.setBackground(new java.awt.Color(255, 255, 255));
        Nombre5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre5.setForeground(new java.awt.Color(0, 0, 0));
        Nombre5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 90, 30));

        Nombre6.setEditable(false);
        Nombre6.setBackground(new java.awt.Color(255, 255, 255));
        Nombre6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre6.setForeground(new java.awt.Color(0, 0, 0));
        Nombre6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 90, 30));

        Nombre7.setEditable(false);
        Nombre7.setBackground(new java.awt.Color(255, 255, 255));
        Nombre7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre7.setForeground(new java.awt.Color(0, 0, 0));
        Nombre7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 110, 90, 30));

        Nombre8.setEditable(false);
        Nombre8.setBackground(new java.awt.Color(255, 255, 255));
        Nombre8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre8.setForeground(new java.awt.Color(0, 0, 0));
        Nombre8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 140, 90, 30));

        Nombre9.setEditable(false);
        Nombre9.setBackground(new java.awt.Color(255, 255, 255));
        Nombre9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre9.setForeground(new java.awt.Color(0, 0, 0));
        Nombre9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 190, 90, 30));

        Nombre10.setEditable(false);
        Nombre10.setBackground(new java.awt.Color(255, 255, 255));
        Nombre10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre10.setForeground(new java.awt.Color(0, 0, 0));
        Nombre10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 220, 90, 30));

        Nombre11.setEditable(false);
        Nombre11.setBackground(new java.awt.Color(56, 56, 56));
        Nombre11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre11.setForeground(new java.awt.Color(0, 0, 0));
        Nombre11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 90, 30));

        Nombre12.setEditable(false);
        Nombre12.setBackground(new java.awt.Color(56, 56, 56));
        Nombre12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre12.setForeground(new java.awt.Color(0, 0, 0));
        Nombre12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 90, 30));

        Nombre13.setEditable(false);
        Nombre13.setBackground(new java.awt.Color(56, 56, 56));
        Nombre13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre13.setForeground(new java.awt.Color(0, 0, 0));
        Nombre13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, 90, 30));

        Nombre14.setEditable(false);
        Nombre14.setBackground(new java.awt.Color(56, 56, 56));
        Nombre14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre14.setForeground(new java.awt.Color(0, 0, 0));
        Nombre14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 140, 90, 30));

        Nombre15.setEditable(false);
        Nombre15.setBackground(new java.awt.Color(56, 56, 56));
        Nombre15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre15.setForeground(new java.awt.Color(0, 0, 0));
        Nombre15.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 90, 30));

        Nombre16.setEditable(false);
        Nombre16.setBackground(new java.awt.Color(56, 56, 56));
        Nombre16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre16.setForeground(new java.awt.Color(0, 0, 0));
        Nombre16.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 90, 30));

        Nombre17.setEditable(false);
        Nombre17.setBackground(new java.awt.Color(56, 56, 56));
        Nombre17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre17.setForeground(new java.awt.Color(0, 0, 0));
        Nombre17.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre17, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 90, 30));

        Nombre18.setEditable(false);
        Nombre18.setBackground(new java.awt.Color(56, 56, 56));
        Nombre18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre18.setForeground(new java.awt.Color(0, 0, 0));
        Nombre18.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre18, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, 90, 30));

        Nombre19.setEditable(false);
        Nombre19.setBackground(new java.awt.Color(56, 56, 56));
        Nombre19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre19.setForeground(new java.awt.Color(0, 0, 0));
        Nombre19.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 90, 30));

        Nombre20.setEditable(false);
        Nombre20.setBackground(new java.awt.Color(56, 56, 56));
        Nombre20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre20.setForeground(new java.awt.Color(0, 0, 0));
        Nombre20.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 90, 30));

        Punto3.setBackground(new java.awt.Color(255, 255, 255));
        Punto3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto3.setForeground(new java.awt.Color(0, 0, 0));
        Punto3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 30, 30));

        Punto4.setBackground(new java.awt.Color(255, 255, 255));
        Punto4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto4.setForeground(new java.awt.Color(0, 0, 0));
        Punto4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 30, 30));

        Punto5.setBackground(new java.awt.Color(255, 255, 255));
        Punto5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto5.setForeground(new java.awt.Color(0, 0, 0));
        Punto5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 30, 30));

        Punto6.setBackground(new java.awt.Color(255, 255, 255));
        Punto6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto6.setForeground(new java.awt.Color(0, 0, 0));
        Punto6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 30, 30));

        Punto7.setBackground(new java.awt.Color(255, 255, 255));
        Punto7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto7.setForeground(new java.awt.Color(0, 0, 0));
        Punto7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 110, 30, 30));

        Punto8.setBackground(new java.awt.Color(255, 255, 255));
        Punto8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto8.setForeground(new java.awt.Color(0, 0, 0));
        Punto8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 140, 30, 30));

        Punto9.setBackground(new java.awt.Color(255, 255, 255));
        Punto9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto9.setForeground(new java.awt.Color(0, 0, 0));
        Punto9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 190, 30, 30));

        Punto10.setBackground(new java.awt.Color(255, 255, 255));
        Punto10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto10.setForeground(new java.awt.Color(0, 0, 0));
        Punto10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 220, 30, 30));

        Punto11.setEditable(false);
        Punto11.setBackground(new java.awt.Color(56, 56, 56));
        Punto11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto11.setForeground(new java.awt.Color(0, 0, 0));
        Punto11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 30, 30));

        Punto12.setEditable(false);
        Punto12.setBackground(new java.awt.Color(56, 56, 56));
        Punto12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto12.setForeground(new java.awt.Color(0, 0, 0));
        Punto12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 30, 30));

        Punto13.setEditable(false);
        Punto13.setBackground(new java.awt.Color(56, 56, 56));
        Punto13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto13.setForeground(new java.awt.Color(0, 0, 0));
        Punto13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 30, 30));

        Punto14.setEditable(false);
        Punto14.setBackground(new java.awt.Color(56, 56, 56));
        Punto14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto14.setForeground(new java.awt.Color(0, 0, 0));
        Punto14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, 30, 30));

        Punto15.setEditable(false);
        Punto15.setBackground(new java.awt.Color(56, 56, 56));
        Punto15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto15.setForeground(new java.awt.Color(0, 0, 0));
        Punto15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 30, 30));

        Punto16.setEditable(false);
        Punto16.setBackground(new java.awt.Color(56, 56, 56));
        Punto16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto16.setForeground(new java.awt.Color(0, 0, 0));
        Punto16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 30, 30));

        Punto17.setEditable(false);
        Punto17.setBackground(new java.awt.Color(56, 56, 56));
        Punto17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto17.setForeground(new java.awt.Color(0, 0, 0));
        Punto17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto17, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 30, 30));

        Punto18.setEditable(false);
        Punto18.setBackground(new java.awt.Color(56, 56, 56));
        Punto18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto18.setForeground(new java.awt.Color(0, 0, 0));
        Punto18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 30, 30));

        Punto19.setEditable(false);
        Punto19.setBackground(new java.awt.Color(56, 56, 56));
        Punto19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto19.setForeground(new java.awt.Color(0, 0, 0));
        Punto19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 30, 30));

        Punto20.setEditable(false);
        Punto20.setBackground(new java.awt.Color(56, 56, 56));
        Punto20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto20.setForeground(new java.awt.Color(0, 0, 0));
        Punto20.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Punto20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto20, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 30, 30));

        Ganador.setEditable(false);
        Ganador.setBackground(new java.awt.Color(56, 56, 56));
        Ganador.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Ganador.setForeground(new java.awt.Color(255, 255, 255));
        Ganador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ganador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 260, 60));

        GanadorPunto.setEditable(false);
        GanadorPunto.setBackground(new java.awt.Color(56, 56, 56));
        GanadorPunto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        GanadorPunto.setForeground(new java.awt.Color(0, 0, 0));
        GanadorPunto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GanadorPunto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(GanadorPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 30, 30));

        Ronda1.setBackground(new java.awt.Color(56, 56, 56));
        Ronda1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Ronda1.setForeground(new java.awt.Color(255, 255, 255));
        Ronda1.setText("Ronda1");
        Ronda1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ronda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ronda1ActionPerformed(evt);
            }
        });
        getContentPane().add(Ronda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 260, 60));

        CuartosFinal.setBackground(new java.awt.Color(56, 56, 56));
        CuartosFinal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CuartosFinal.setForeground(new java.awt.Color(255, 255, 255));
        CuartosFinal.setText("Cuartos de Final");
        CuartosFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CuartosFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuartosFinalActionPerformed(evt);
            }
        });
        getContentPane().add(CuartosFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 260, 60));

        SemiFinal.setBackground(new java.awt.Color(56, 56, 56));
        SemiFinal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SemiFinal.setForeground(new java.awt.Color(255, 255, 255));
        SemiFinal.setText("SemiFinal");
        SemiFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SemiFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemiFinalActionPerformed(evt);
            }
        });
        getContentPane().add(SemiFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 260, 60));

        Final.setBackground(new java.awt.Color(56, 56, 56));
        Final.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Final.setForeground(new java.awt.Color(255, 255, 255));
        Final.setText("Final");
        Final.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalActionPerformed(evt);
            }
        });
        getContentPane().add(Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 260, 60));

        Reset1.setBackground(new java.awt.Color(56, 56, 56));
        Reset1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Reset1.setForeground(new java.awt.Color(255, 255, 255));
        Reset1.setText("Otro Torneo");
        Reset1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(Reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 130, 60));

        Reset.setBackground(new java.awt.Color(56, 56, 56));
        Reset.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Nuevo");
        Reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 130, 60));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CuartosFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuartosFinalActionPerformed

        JTextField[] nombres = {Nombre11, Nombre12, Nombre13, Nombre14};
        JTextField[] puntos = {Punto11, Punto12, Punto13, Punto14};
        JTextField[] resultadoNombres = {Nombre16, Nombre18};
        JTextField[] resultadoPuntos = {Punto15, Punto16, Punto17, Punto18};

        String Resultado = ganador.Calculos(nombres, puntos, resultadoNombres, resultadoPuntos);

        if (Resultado.equals("")) {
            JOptionPane.showMessageDialog(null, "Felicidades a los participantes por pasar a la Semi Final");
            CuartosFinal.setVisible(false);
            SemiFinal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, Resultado);
        }

    }//GEN-LAST:event_CuartosFinalActionPerformed

    private void SemiFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemiFinalActionPerformed

        JTextField[] nombres = {Nombre15, Nombre16, Nombre17, Nombre18};
        JTextField[] puntos = {Punto15, Punto16, Punto17, Punto18};
        JTextField[] resultadoNombres = {Nombre19, Nombre20};
        JTextField[] resultadoPuntos = {Punto19, Punto20};

        String Resultado = ganador.Calculos(nombres, puntos, resultadoNombres, resultadoPuntos);

        if (Resultado.equals("")) {
            JOptionPane.showMessageDialog(null, "Bienvenidos a la final, que sera entre los participantes\n" + Nombre19.getText() + " VS " + Nombre20.getText());
            SemiFinal.setVisible(false);
            Final.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, Resultado);
        }

    }//GEN-LAST:event_SemiFinalActionPerformed

    private void FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalActionPerformed
        JTextField[] nombres = {Nombre19, Nombre20};
        JTextField[] puntos = {Punto19, Punto20};
        JTextField[] resultadoNombres = {Ganador};
        JTextField[] resultadoPuntos = {GanadorPunto};

        String Resultado = ganador.Calculos(nombres, puntos, resultadoNombres, resultadoPuntos);

        Ganador.setBackground(new Color(56, 56, 56));

        if (Resultado.equals("")) {
            JOptionPane.showMessageDialog(null, "Felicidades a Gandor del Torneo " + Ganador.getText());
            Final.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, Resultado);
        }
    }//GEN-LAST:event_FinalActionPerformed

    private void Ronda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ronda1ActionPerformed

        JTextField[] nombres = {Nombre3, Nombre4, Nombre5, Nombre6, Nombre7, Nombre8, Nombre9, Nombre10};
        JTextField[] puntos = {Punto3, Punto4, Punto5, Punto6, Punto7, Punto8, Punto9, Punto10};
        JTextField[] resultadoNombres = {Nombre17, Nombre12, Nombre15, Nombre14};
        JTextField[] resultadoPuntos = {Punto11, Punto12, Punto13, Punto14};

        String Resultado = ganador.Calculos(nombres, puntos, resultadoNombres, resultadoPuntos);

        Nombre11.setText(Nombre1.getText());
        Nombre13.setText(Nombre2.getText());
        Nombre11.setBackground(new Color(255, 255, 255));
        Nombre13.setBackground(new Color(255, 255, 255));

        if (Resultado.equals("")) {
            JOptionPane.showMessageDialog(null, "Felicidades a los participantes por pasar a los Cuartos de iFinal");
            Ronda1.setVisible(false);
            CuartosFinal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, Resultado);
        }

    }//GEN-LAST:event_Ronda1ActionPerformed

    private void Reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset1ActionPerformed
        new EnArbol10().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Reset1ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ResetActionPerformed

    private void cargarParticipantes() {
        int x = 1;
        List<Participante> data = Participantes.getParticipantes();
        for (Participante p : data) {
            participantes.addRow(new Object[]{p.getNombre()});
        }
        Collections.shuffle(data);

        for (Participante p : data) {
            switch (x) {
                case 1 ->
                    Nombre1.setText(p.getNombre());
                case 2 ->
                    Nombre2.setText(p.getNombre());
                case 3 ->
                    Nombre3.setText(p.getNombre());
                case 4 ->
                    Nombre4.setText(p.getNombre());
                case 5 ->
                    Nombre5.setText(p.getNombre());
                case 6 ->
                    Nombre6.setText(p.getNombre());
                case 7 ->
                    Nombre7.setText(p.getNombre());
                case 8 ->
                    Nombre8.setText(p.getNombre());
                case 9 ->
                    Nombre9.setText(p.getNombre());
                case 10 ->
                    Nombre10.setText(p.getNombre());
                default -> {
                }
            }

            x++;
        }
        if (Nombre10.getText().isEmpty()) {
            Nombre10.setText("(no hay 10⏳)");
            Punto9.setEditable(false);
            Punto10.setEditable(false);
            Punto9.setText("0");
            Punto10.setText("0");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnArbol10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnArbol10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnArbol10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnArbol10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnArbol10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CuartosFinal;
    private javax.swing.JButton Final;
    private javax.swing.JTextField Ganador;
    private javax.swing.JTextField GanadorPunto;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JTextField Nombre10;
    private javax.swing.JTextField Nombre11;
    private javax.swing.JTextField Nombre12;
    private javax.swing.JTextField Nombre13;
    private javax.swing.JTextField Nombre14;
    private javax.swing.JTextField Nombre15;
    private javax.swing.JTextField Nombre16;
    private javax.swing.JTextField Nombre17;
    private javax.swing.JTextField Nombre18;
    private javax.swing.JTextField Nombre19;
    private javax.swing.JTextField Nombre2;
    private javax.swing.JTextField Nombre20;
    private javax.swing.JTextField Nombre3;
    private javax.swing.JTextField Nombre4;
    private javax.swing.JTextField Nombre5;
    private javax.swing.JTextField Nombre6;
    private javax.swing.JTextField Nombre7;
    private javax.swing.JTextField Nombre8;
    private javax.swing.JTextField Nombre9;
    private javax.swing.JTextField Punto10;
    private javax.swing.JTextField Punto11;
    private javax.swing.JTextField Punto12;
    private javax.swing.JTextField Punto13;
    private javax.swing.JTextField Punto14;
    private javax.swing.JTextField Punto15;
    private javax.swing.JTextField Punto16;
    private javax.swing.JTextField Punto17;
    private javax.swing.JTextField Punto18;
    private javax.swing.JTextField Punto19;
    private javax.swing.JTextField Punto20;
    private javax.swing.JTextField Punto3;
    private javax.swing.JTextField Punto4;
    private javax.swing.JTextField Punto5;
    private javax.swing.JTextField Punto6;
    private javax.swing.JTextField Punto7;
    private javax.swing.JTextField Punto8;
    private javax.swing.JTextField Punto9;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Reset1;
    private javax.swing.JButton Ronda1;
    private javax.swing.JButton SemiFinal;
    private javax.swing.JTable TableParticipantes;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
