/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.arbol;

import clases.Participante;
import clases.Participantes;
import java.awt.Image;
import java.util.Collections;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ventanas.Inicio;

/**
 *
 * @author MINEDUCYT
 */
public class EnArbol6 extends javax.swing.JFrame {

    DefaultTableModel participantes;

    public EnArbol6() {
        initComponents();
        this.setLocationRelativeTo(null);

        participantes = new DefaultTableModel();
        participantes.addColumn("ID / Participante");
        TableParticipantes.setModel(participantes);

        ImageIcon wallpaper = new ImageIcon("src/img/Wallpaper2.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        LabelWallpaper.setIcon(icon);
        
        SemiFinal.setVisible(false);
        Final.setVisible(false);

        cargarParticipantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TableParticipantes = new javax.swing.JTable();
        Nombre2 = new javax.swing.JTextField();
        Nombre1 = new javax.swing.JTextField();
        Nombre3 = new javax.swing.JTextField();
        Nombre4 = new javax.swing.JTextField();
        Nombre5 = new javax.swing.JTextField();
        Nombre6 = new javax.swing.JTextField();
        Nombre7 = new javax.swing.JTextField();
        Nombre8 = new javax.swing.JTextField();
        Nombre9 = new javax.swing.JTextField();
        Nombre10 = new javax.swing.JTextField();
        Ganador = new javax.swing.JTextField();
        Punto1 = new javax.swing.JTextField();
        Punto2 = new javax.swing.JTextField();
        Punto3 = new javax.swing.JTextField();
        Punto4 = new javax.swing.JTextField();
        Punto5 = new javax.swing.JTextField();
        Punto6 = new javax.swing.JTextField();
        Punto7 = new javax.swing.JTextField();
        Punto8 = new javax.swing.JTextField();
        Punto9 = new javax.swing.JTextField();
        Punto10 = new javax.swing.JTextField();
        Ronda1 = new javax.swing.JButton();
        SemiFinal = new javax.swing.JButton();
        Final = new javax.swing.JButton();
        Reset1 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TableParticipantes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 130));

        Nombre2.setEditable(false);
        Nombre2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, 30));

        Nombre1.setEditable(false);
        Nombre1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 90, 30));

        Nombre3.setEditable(false);
        Nombre3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 90, 30));

        Nombre4.setEditable(false);
        Nombre4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 90, 30));

        Nombre5.setEditable(false);
        Nombre5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 90, 30));

        Nombre6.setEditable(false);
        Nombre6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 90, 30));

        Nombre7.setEditable(false);
        Nombre7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, 30));

        Nombre8.setEditable(false);
        Nombre8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 90, 30));

        Nombre9.setEditable(false);
        Nombre9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 90, 30));

        Nombre10.setEditable(false);
        Nombre10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 90, 30));

        Ganador.setEditable(false);
        Ganador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Ganador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ganador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 210, 60));

        Punto1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 30, 30));

        Punto2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 30, 30));

        Punto3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 30, 30));

        Punto4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 30, 30));

        Punto5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 30, 30));

        Punto6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 30, 30));

        Punto7.setEditable(false);
        Punto7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 30, 30));

        Punto8.setEditable(false);
        Punto8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 30, 30));

        Punto9.setEditable(false);
        Punto9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 30, 30));

        Punto10.setEditable(false);
        Punto10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 30, 30));

        Ronda1.setText("Ronda1");
        Ronda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ronda1ActionPerformed(evt);
            }
        });
        getContentPane().add(Ronda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 210, 70));

        SemiFinal.setText("SemiFinal");
        SemiFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemiFinalActionPerformed(evt);
            }
        });
        getContentPane().add(SemiFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 210, 70));

        Final.setText("Final");
        Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalActionPerformed(evt);
            }
        });
        getContentPane().add(Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 210, 70));

        Reset1.setText("Otro Torneo");
        Reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(Reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 100, 70));

        Reset.setText("Nuevo");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 110, 70));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ronda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ronda1ActionPerformed
        try {
            if (Integer.parseInt(Punto1.getText()) > Integer.parseInt(Punto2.getText())) {
                Nombre7.setText(Nombre1.getText());
            } else {
                Nombre7.setText(Nombre2.getText());
            }

            if (Integer.parseInt(Punto3.getText()) > Integer.parseInt(Punto4.getText())) {
                Nombre8.setText(Nombre3.getText());
            } else {
                Nombre8.setText(Nombre4.getText());
            }

            if (Integer.parseInt(Punto5.getText()) > Integer.parseInt(Punto6.getText())) {
                Nombre10.setText(Nombre5.getText());
            } else {
                Nombre10.setText(Nombre6.getText());
            }

            if (Nombre6.getText().equals("(no hay 6⏳)")) {
                Nombre10.setText(Nombre5.getText());
            }
            Ronda1.setVisible(false);
            SemiFinal.setVisible(true);
            Punto1.setEditable(false);
            Punto2.setEditable(false);
            Punto3.setEditable(false);
            Punto4.setEditable(false);
            Punto5.setEditable(false);
            Punto6.setEditable(false);
            Punto7.setEditable(true);
            Punto8.setEditable(true);
        } catch (Exception e) {
            Nombre7.setText("");
            Nombre8.setText("");
            JOptionPane.showMessageDialog(this, "Hay caracteres no validos.\n Error(" + e + ")");
        }
    }//GEN-LAST:event_Ronda1ActionPerformed

    private void SemiFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemiFinalActionPerformed
        try {
            if (Integer.parseInt(Punto7.getText()) > Integer.parseInt(Punto8.getText())) {
                Nombre9.setText("(Esperando⏳)");
                Nombre9.setText("(Esperando⏳)");
            } else {
                Nombre9.setText(Nombre8.getText());
            }

            SemiFinal.setVisible(false);
            Final.setVisible(true);
            Punto7.setEditable(false);
            Punto8.setEditable(false);
            Punto9.setEditable(true);
            Punto10.setEditable(true);
        } catch (Exception e) {
            Nombre9.setText("");
            JOptionPane.showMessageDialog(this, "Hay caracteres no validos.\n Error(" + e + ")");
        }
    }//GEN-LAST:event_SemiFinalActionPerformed

    private void FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalActionPerformed
        try {
            if (Integer.parseInt(Punto9.getText()) > Integer.parseInt(Punto10.getText())) {
                Ganador.setText(Nombre9.getText());
            } else {
                Ganador.setText(Nombre10.getText());
            }
            Final.setVisible(false);
            Punto9.setEditable(false);
            Punto10.setEditable(false);
        } catch (Exception e) {
            Ganador.setText("");
            JOptionPane.showMessageDialog(this, "Hay caracteres no validos.\n Error(" + e + ")");
        }
    }//GEN-LAST:event_FinalActionPerformed

    private void Reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset1ActionPerformed
        new EnArbol6().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Reset1ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ResetActionPerformed

    private void cargarParticipantes() {
        int x = 1;
        List<Participante> data = Participantes.getParticipantes();
        for (Participante p : data) {
            participantes.addRow(new Object[]{p.getNombre()});
        }
        Collections.shuffle(data);

        for (Participante p : data) {
            switch (x) {
                case 1 ->
                    Nombre1.setText(p.getNombre());
                case 2 ->
                    Nombre2.setText(p.getNombre());
                case 3 ->
                    Nombre3.setText(p.getNombre());
                case 4 ->
                    Nombre4.setText(p.getNombre());
                case 5 ->
                    Nombre5.setText(p.getNombre());
                case 6 ->
                    Nombre6.setText(p.getNombre());
                default -> {
                }
            }
            x++;
        }
        if (Nombre6.getText().isEmpty()) {
            Nombre6.setText("(no hay 6⏳)");
            Punto5.setEditable(false);
            Punto6.setEditable(false);
            Punto5.setText("0");
            Punto6.setText("0");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnArbol6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnArbol6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnArbol6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnArbol6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnArbol6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Final;
    private javax.swing.JTextField Ganador;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JTextField Nombre10;
    private javax.swing.JTextField Nombre2;
    private javax.swing.JTextField Nombre3;
    private javax.swing.JTextField Nombre4;
    private javax.swing.JTextField Nombre5;
    private javax.swing.JTextField Nombre6;
    private javax.swing.JTextField Nombre7;
    private javax.swing.JTextField Nombre8;
    private javax.swing.JTextField Nombre9;
    private javax.swing.JTextField Punto1;
    private javax.swing.JTextField Punto10;
    private javax.swing.JTextField Punto2;
    private javax.swing.JTextField Punto3;
    private javax.swing.JTextField Punto4;
    private javax.swing.JTextField Punto5;
    private javax.swing.JTextField Punto6;
    private javax.swing.JTextField Punto7;
    private javax.swing.JTextField Punto8;
    private javax.swing.JTextField Punto9;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Reset1;
    private javax.swing.JButton Ronda1;
    private javax.swing.JButton SemiFinal;
    private javax.swing.JTable TableParticipantes;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
