/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.arbol;

import clases.Participante;
import clases.Participantes;
import java.awt.Image;
import java.util.Collections;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ventanas.Inicio;

/**
 *
 * @author MINEDUCYT
 */
public class EnArbol10 extends javax.swing.JFrame {

    DefaultTableModel participantes;

    public EnArbol10() {
        initComponents();
        this.setLocationRelativeTo(null);

        participantes = new DefaultTableModel();
        participantes.addColumn("ID / Participante");
        TableParticipantes.setModel(participantes);

        ImageIcon wallpaper = new ImageIcon("src/img/Wallpaper2.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        LabelWallpaper.setIcon(icon);
        
        Ronda2.setVisible(false);
        SemiFinal.setVisible(false);
        Final.setVisible(false);
        cargarParticipantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TableParticipantes = new javax.swing.JTable();
        Nombre1 = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JTextField();
        Nombre3 = new javax.swing.JTextField();
        Nombre4 = new javax.swing.JTextField();
        Nombre5 = new javax.swing.JTextField();
        Nombre6 = new javax.swing.JTextField();
        Nombre7 = new javax.swing.JTextField();
        Nombre8 = new javax.swing.JTextField();
        Nombre9 = new javax.swing.JTextField();
        Nombre10 = new javax.swing.JTextField();
        Nombre13 = new javax.swing.JTextField();
        Nombre14 = new javax.swing.JTextField();
        Nombre15 = new javax.swing.JTextField();
        Nombre16 = new javax.swing.JTextField();
        Nombre17 = new javax.swing.JTextField();
        Nombre18 = new javax.swing.JTextField();
        Nombre19 = new javax.swing.JTextField();
        Nombre20 = new javax.swing.JTextField();
        Nombre21 = new javax.swing.JTextField();
        Nombre22 = new javax.swing.JTextField();
        Punto3 = new javax.swing.JTextField();
        Punto4 = new javax.swing.JTextField();
        Punto5 = new javax.swing.JTextField();
        Punto6 = new javax.swing.JTextField();
        Punto7 = new javax.swing.JTextField();
        Punto8 = new javax.swing.JTextField();
        Punto9 = new javax.swing.JTextField();
        Punto10 = new javax.swing.JTextField();
        Punto13 = new javax.swing.JTextField();
        Punto14 = new javax.swing.JTextField();
        Punto15 = new javax.swing.JTextField();
        Punto16 = new javax.swing.JTextField();
        Punto17 = new javax.swing.JTextField();
        Punto18 = new javax.swing.JTextField();
        Punto19 = new javax.swing.JTextField();
        Punto20 = new javax.swing.JTextField();
        Punto21 = new javax.swing.JTextField();
        Punto22 = new javax.swing.JTextField();
        Ganador = new javax.swing.JTextField();
        Ronda1 = new javax.swing.JButton();
        Ronda2 = new javax.swing.JButton();
        SemiFinal = new javax.swing.JButton();
        Final = new javax.swing.JButton();
        Reset1 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TableParticipantes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 220));

        Nombre1.setEditable(false);
        Nombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombre1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 120, 30));

        Nombre2.setEditable(false);
        Nombre2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombre2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 160, 120, 30));

        Nombre3.setEditable(false);
        Nombre3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 90, 30));

        Nombre4.setEditable(false);
        Nombre4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 90, 30));

        Nombre5.setEditable(false);
        Nombre5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 90, 30));

        Nombre6.setEditable(false);
        Nombre6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 90, 30));

        Nombre7.setEditable(false);
        Nombre7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 220, 90, 30));

        Nombre8.setEditable(false);
        Nombre8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 250, 90, 30));

        Nombre9.setEditable(false);
        Nombre9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 300, 90, 30));

        Nombre10.setEditable(false);
        Nombre10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 330, 90, 30));

        Nombre13.setEditable(false);
        Nombre13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 90, 30));

        Nombre14.setEditable(false);
        Nombre14.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 90, 30));

        Nombre15.setEditable(false);
        Nombre15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, 90, 30));

        Nombre16.setEditable(false);
        Nombre16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, 90, 30));

        Nombre17.setEditable(false);
        Nombre17.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 90, 30));

        Nombre18.setEditable(false);
        Nombre18.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 90, 30));

        Nombre19.setEditable(false);
        Nombre19.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre19, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 90, 30));

        Nombre20.setEditable(false);
        Nombre20.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre20, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 90, 30));

        Nombre21.setEditable(false);
        Nombre21.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 90, 30));

        Nombre22.setEditable(false);
        Nombre22.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre22, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 90, 30));

        Punto3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 30, 30));

        Punto4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 30, 30));

        Punto5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 30, 30));

        Punto6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 30, 30));

        Punto7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Punto7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 220, 30, 30));

        Punto8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Punto8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 250, 30, 30));

        Punto9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Punto9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 300, 30, 30));

        Punto10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Punto10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 330, 30, 30));

        Punto13.setEditable(false);
        Punto13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 30, 30));

        Punto14.setEditable(false);
        Punto14.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 30, 30));

        Punto15.setEditable(false);
        Punto15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Punto15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 220, 30, 30));

        Punto16.setEditable(false);
        Punto16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Punto16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, 30, 30));

        Punto17.setEditable(false);
        Punto17.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 30, 30));

        Punto18.setEditable(false);
        Punto18.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 30, 30));

        Punto19.setEditable(false);
        Punto19.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Punto19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto19, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, 30, 30));

        Punto20.setEditable(false);
        Punto20.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Punto20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto20, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, 30, 30));

        Punto21.setEditable(false);
        Punto21.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Punto21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 30, 30));

        Punto22.setEditable(false);
        Punto22.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Punto22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto22, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 30, 30));

        Ganador.setEditable(false);
        Ganador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Ganador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ganador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 260, 60));

        Ronda1.setText("Ronda1");
        Ronda1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ronda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ronda1ActionPerformed(evt);
            }
        });
        getContentPane().add(Ronda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 260, 60));

        Ronda2.setText("Ronda2");
        Ronda2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ronda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ronda2ActionPerformed(evt);
            }
        });
        getContentPane().add(Ronda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 260, 60));

        SemiFinal.setText("SemiFinal");
        SemiFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SemiFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemiFinalActionPerformed(evt);
            }
        });
        getContentPane().add(SemiFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 260, 60));

        Final.setText("Final");
        Final.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalActionPerformed(evt);
            }
        });
        getContentPane().add(Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 260, 60));

        Reset1.setText("Otro Torneo");
        Reset1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(Reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 130, 60));

        Reset.setText("Nuevo");
        Reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 130, 60));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ronda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ronda2ActionPerformed
        try {
            if (Integer.parseInt(Punto13.getText()) > Integer.parseInt(Punto14.getText())) {
                Nombre17.setText(Nombre13.getText());
            } else {
                Nombre17.setText(Nombre14.getText());
            }
            if (Integer.parseInt(Punto15.getText()) > Integer.parseInt(Punto16.getText())) {
                Nombre19.setText(Nombre15.getText());
            } else {
                Nombre19.setText(Nombre16.getText());
            }
            Ronda2.setVisible(false);
            SemiFinal.setVisible(true);

            Punto13.setEditable(false);
            Punto14.setEditable(false);
            Punto15.setEditable(false);
            Punto16.setEditable(false);
            Punto17.setEditable(true);
            Punto18.setEditable(true);
            Punto19.setEditable(true);
            Punto20.setEditable(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hay caracteres no validos.\n Error(" + e + ")");
            Nombre17.setText("");
            Nombre18.setText("");
            Nombre19.setText("");
            Nombre20.setText("");
        }
    }//GEN-LAST:event_Ronda2ActionPerformed

    private void SemiFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemiFinalActionPerformed
        try {
            if (Integer.parseInt(Punto17.getText()) > Integer.parseInt(Punto18.getText())) {
                Nombre21.setText(Nombre17.getText());
            } else {
                Nombre21.setText(Nombre18.getText());
            }

            if (Integer.parseInt(Punto19.getText()) > Integer.parseInt(Punto20.getText())) {
                Nombre22.setText(Nombre19.getText());
            } else {
                Nombre22.setText(Nombre20.getText());
            }
            SemiFinal.setVisible(false);
            Final.setVisible(true);

            Punto17.setEditable(false);
            Punto18.setEditable(false);
            Punto19.setEditable(false);
            Punto20.setEditable(false);
            Punto21.setEditable(true);
            Punto22.setEditable(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hay caracteres no validos.\n Error(" + e + ")");
            Nombre21.setText("");
            Nombre22.setText("");
        }
    }//GEN-LAST:event_SemiFinalActionPerformed

    private void FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalActionPerformed
        try {
            if (Integer.parseInt(Punto21.getText()) > Integer.parseInt(Punto22.getText())) {
                Ganador.setText(Nombre21.getText());
            } else {
                Ganador.setText(Nombre22.getText());
            }
            Final.setVisible(false);

            Punto21.setEditable(false);
            Punto22.setEditable(false);
        } catch (Exception e) {
            Ganador.setText("");
            JOptionPane.showMessageDialog(this, "Hay caracteres no validos.\n Error(" + e + ")");
        }
    }//GEN-LAST:event_FinalActionPerformed

    private void Ronda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ronda1ActionPerformed
        try {

            Nombre13.setText(Nombre1.getText());
            Nombre15.setText(Nombre2.getText());

            if (Integer.parseInt(Punto3.getText()) > Integer.parseInt(Punto4.getText())) {
                Nombre14.setText(Nombre3.getText());
            } else {
                Nombre14.setText(Nombre4.getText());
            }

            if (Integer.parseInt(Punto5.getText()) > Integer.parseInt(Punto6.getText())) {
                Nombre17.setText("(Esperando⏳)");
                Nombre18.setText(Nombre5.getText());
            } else {
                Nombre17.setText("(Esperando⏳)");
                Nombre18.setText(Nombre6.getText());
            }

            if (Integer.parseInt(Punto7.getText()) > Integer.parseInt(Punto8.getText())) {
                Nombre16.setText(Nombre7.getText());
            } else {
                Nombre16.setText(Nombre8.getText());
            }
            if (Integer.parseInt(Punto9.getText()) > Integer.parseInt(Punto10.getText())) {
                Nombre19.setText("(Esperando⏳)");
                Nombre20.setText(Nombre9.getText());
            } else {
                Nombre19.setText("(Esperando⏳)");
                Nombre20.setText(Nombre10.getText());
            }

            if (Nombre10.getText().equals("(no hay 10⏳)")) {
                Nombre20.setText(Nombre16.getText());
                Nombre16.setText(Nombre9.getText());
            }

            Ronda1.setVisible(false);
            Ronda2.setVisible(true);
            Punto3.setEditable(false);
            Punto4.setEditable(false);
            Punto5.setEditable(false);
            Punto6.setEditable(false);
            Punto7.setEditable(false);
            Punto8.setEditable(false);
            Punto9.setEditable(false);
            Punto10.setEditable(false);
            Punto13.setEditable(true);
            Punto14.setEditable(true);
            Punto15.setEditable(true);
            Punto16.setEditable(true);
        } catch (Exception e) {
            Nombre13.setText("");
            Nombre14.setText("");
            Nombre15.setText("");
            Nombre16.setText("");
            JOptionPane.showMessageDialog(this, "Hay caracteres no validos.\n Error(" + e + ")");
        }
    }//GEN-LAST:event_Ronda1ActionPerformed

    private void Reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset1ActionPerformed
        new EnArbol10().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Reset1ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ResetActionPerformed

    private void cargarParticipantes() {
        int x = 1;
        List<Participante> data = Participantes.getParticipantes();
        for (Participante p : data) {
            participantes.addRow(new Object[]{p.getNombre()});
        }
        Collections.shuffle(data);

        for (Participante p : data) {
            switch (x) {
                case 1 ->
                    Nombre1.setText(p.getNombre());
                case 2 ->
                    Nombre2.setText(p.getNombre());
                case 3 ->
                    Nombre3.setText(p.getNombre());
                case 4 ->
                    Nombre4.setText(p.getNombre());
                case 5 ->
                    Nombre5.setText(p.getNombre());
                case 6 ->
                    Nombre6.setText(p.getNombre());
                case 7 ->
                    Nombre7.setText(p.getNombre());
                case 8 ->
                    Nombre8.setText(p.getNombre());
                case 9 ->
                    Nombre9.setText(p.getNombre());
                case 10 ->
                    Nombre10.setText(p.getNombre());
                default -> {
                }
            }

            x++;
        }
        if (Nombre10.getText().isEmpty()) {
            Nombre10.setText("(no hay 10⏳)");
            Punto9.setEditable(false);
            Punto10.setEditable(false);
            Punto9.setText("0");
            Punto10.setText("0");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnArbol10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnArbol10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnArbol10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnArbol10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnArbol10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Final;
    private javax.swing.JTextField Ganador;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JTextField Nombre10;
    private javax.swing.JTextField Nombre13;
    private javax.swing.JTextField Nombre14;
    private javax.swing.JTextField Nombre15;
    private javax.swing.JTextField Nombre16;
    private javax.swing.JTextField Nombre17;
    private javax.swing.JTextField Nombre18;
    private javax.swing.JTextField Nombre19;
    private javax.swing.JTextField Nombre2;
    private javax.swing.JTextField Nombre20;
    private javax.swing.JTextField Nombre21;
    private javax.swing.JTextField Nombre22;
    private javax.swing.JTextField Nombre3;
    private javax.swing.JTextField Nombre4;
    private javax.swing.JTextField Nombre5;
    private javax.swing.JTextField Nombre6;
    private javax.swing.JTextField Nombre7;
    private javax.swing.JTextField Nombre8;
    private javax.swing.JTextField Nombre9;
    private javax.swing.JTextField Punto10;
    private javax.swing.JTextField Punto13;
    private javax.swing.JTextField Punto14;
    private javax.swing.JTextField Punto15;
    private javax.swing.JTextField Punto16;
    private javax.swing.JTextField Punto17;
    private javax.swing.JTextField Punto18;
    private javax.swing.JTextField Punto19;
    private javax.swing.JTextField Punto20;
    private javax.swing.JTextField Punto21;
    private javax.swing.JTextField Punto22;
    private javax.swing.JTextField Punto3;
    private javax.swing.JTextField Punto4;
    private javax.swing.JTextField Punto5;
    private javax.swing.JTextField Punto6;
    private javax.swing.JTextField Punto7;
    private javax.swing.JTextField Punto8;
    private javax.swing.JTextField Punto9;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Reset1;
    private javax.swing.JButton Ronda1;
    private javax.swing.JButton Ronda2;
    private javax.swing.JButton SemiFinal;
    private javax.swing.JTable TableParticipantes;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
