/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.arbol;

import clases.Participante;
import clases.Participantes;
import java.awt.Color;
import java.awt.Image;
import java.util.Collections;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ventanas.Inicio;

/**
 *
 * @author MINEDUCYT
 */
public class EnArbol8 extends javax.swing.JFrame {

    DefaultTableModel participantes;
    Color win = Color.GREEN;
    Color lose = Color.RED;
    Color blanco = Color.WHITE;
    Color negro = new Color(56, 56, 56);

    public EnArbol8() {
        initComponents();
        this.setLocationRelativeTo(null);

        participantes = new DefaultTableModel();
        participantes.addColumn("ID / Participante");
        TableParticipantes.setModel(participantes);

        ImageIcon wallpaper = new ImageIcon("src/img/Wallpaper2.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        LabelWallpaper.setIcon(icon);

        SemiFinal.setVisible(false);
        Final.setVisible(false);

        cargarParticipantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TableParticipantes = new javax.swing.JTable();
        Nombre2 = new javax.swing.JTextField();
        Nombre1 = new javax.swing.JTextField();
        Nombre3 = new javax.swing.JTextField();
        Nombre4 = new javax.swing.JTextField();
        Nombre5 = new javax.swing.JTextField();
        Nombre6 = new javax.swing.JTextField();
        Nombre7 = new javax.swing.JTextField();
        Nombre8 = new javax.swing.JTextField();
        Nombre9 = new javax.swing.JTextField();
        Nombre10 = new javax.swing.JTextField();
        Ganador = new javax.swing.JTextField();
        Nombre11 = new javax.swing.JTextField();
        Nombre12 = new javax.swing.JTextField();
        Nombre14 = new javax.swing.JTextField();
        Nombre13 = new javax.swing.JTextField();
        Punto1 = new javax.swing.JTextField();
        Punto2 = new javax.swing.JTextField();
        Punto3 = new javax.swing.JTextField();
        Punto4 = new javax.swing.JTextField();
        Punto5 = new javax.swing.JTextField();
        Punto6 = new javax.swing.JTextField();
        Punto7 = new javax.swing.JTextField();
        Punto8 = new javax.swing.JTextField();
        Punto9 = new javax.swing.JTextField();
        Punto10 = new javax.swing.JTextField();
        Punto11 = new javax.swing.JTextField();
        Punto12 = new javax.swing.JTextField();
        Punto13 = new javax.swing.JTextField();
        Punto14 = new javax.swing.JTextField();
        Ronda1 = new javax.swing.JButton();
        SemiFinal = new javax.swing.JButton();
        Final = new javax.swing.JButton();
        Reset1 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TableParticipantes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 160));

        Nombre2.setEditable(false);
        Nombre2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre2.setForeground(new java.awt.Color(0, 0, 0));
        Nombre2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 100, 30));

        Nombre1.setEditable(false);
        Nombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre1.setForeground(new java.awt.Color(0, 0, 0));
        Nombre1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 100, 30));

        Nombre3.setEditable(false);
        Nombre3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre3.setForeground(new java.awt.Color(0, 0, 0));
        Nombre3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 100, 30));

        Nombre4.setEditable(false);
        Nombre4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre4.setForeground(new java.awt.Color(0, 0, 0));
        Nombre4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 100, 30));

        Nombre5.setEditable(false);
        Nombre5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre5.setForeground(new java.awt.Color(0, 0, 0));
        Nombre5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 100, 30));

        Nombre6.setEditable(false);
        Nombre6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre6.setForeground(new java.awt.Color(0, 0, 0));
        Nombre6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 100, 30));

        Nombre7.setEditable(false);
        Nombre7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre7.setForeground(new java.awt.Color(0, 0, 0));
        Nombre7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 100, 30));

        Nombre8.setEditable(false);
        Nombre8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre8.setForeground(new java.awt.Color(0, 0, 0));
        Nombre8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 100, 30));

        Nombre9.setEditable(false);
        Nombre9.setBackground(new java.awt.Color(56, 56, 56));
        Nombre9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre9.setForeground(new java.awt.Color(0, 0, 0));
        Nombre9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 100, 30));

        Nombre10.setEditable(false);
        Nombre10.setBackground(new java.awt.Color(56, 56, 56));
        Nombre10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre10.setForeground(new java.awt.Color(0, 0, 0));
        Nombre10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 100, 30));

        Ganador.setEditable(false);
        Ganador.setBackground(new java.awt.Color(56, 56, 56));
        Ganador.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Ganador.setForeground(new java.awt.Color(255, 255, 255));
        Ganador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ganador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 220, 60));

        Nombre11.setEditable(false);
        Nombre11.setBackground(new java.awt.Color(56, 56, 56));
        Nombre11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre11.setForeground(new java.awt.Color(0, 0, 0));
        Nombre11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 100, 30));

        Nombre12.setEditable(false);
        Nombre12.setBackground(new java.awt.Color(56, 56, 56));
        Nombre12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre12.setForeground(new java.awt.Color(0, 0, 0));
        Nombre12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 100, 30));

        Nombre14.setEditable(false);
        Nombre14.setBackground(new java.awt.Color(56, 56, 56));
        Nombre14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre14.setForeground(new java.awt.Color(0, 0, 0));
        Nombre14.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 100, 30));

        Nombre13.setEditable(false);
        Nombre13.setBackground(new java.awt.Color(56, 56, 56));
        Nombre13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre13.setForeground(new java.awt.Color(0, 0, 0));
        Nombre13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nombre13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Nombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 100, 30));

        Punto1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto1.setForeground(new java.awt.Color(0, 0, 0));
        Punto1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 30, 30));

        Punto2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto2.setForeground(new java.awt.Color(0, 0, 0));
        Punto2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 30, 30));

        Punto3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto3.setForeground(new java.awt.Color(0, 0, 0));
        Punto3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 30, 30));

        Punto4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto4.setForeground(new java.awt.Color(0, 0, 0));
        Punto4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 30, 30));

        Punto5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto5.setForeground(new java.awt.Color(0, 0, 0));
        Punto5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 30, 30));

        Punto6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto6.setForeground(new java.awt.Color(0, 0, 0));
        Punto6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 30, 30));

        Punto7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto7.setForeground(new java.awt.Color(0, 0, 0));
        Punto7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 30, 30));

        Punto8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto8.setForeground(new java.awt.Color(0, 0, 0));
        Punto8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 30, 30));

        Punto9.setEditable(false);
        Punto9.setBackground(new java.awt.Color(56, 56, 56));
        Punto9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto9.setForeground(new java.awt.Color(0, 0, 0));
        Punto9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 30, 30));

        Punto10.setEditable(false);
        Punto10.setBackground(new java.awt.Color(56, 56, 56));
        Punto10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto10.setForeground(new java.awt.Color(0, 0, 0));
        Punto10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 30, 30));

        Punto11.setEditable(false);
        Punto11.setBackground(new java.awt.Color(56, 56, 56));
        Punto11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto11.setForeground(new java.awt.Color(0, 0, 0));
        Punto11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 30, 30));

        Punto12.setEditable(false);
        Punto12.setBackground(new java.awt.Color(56, 56, 56));
        Punto12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto12.setForeground(new java.awt.Color(0, 0, 0));
        Punto12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 30, 30));

        Punto13.setEditable(false);
        Punto13.setBackground(new java.awt.Color(56, 56, 56));
        Punto13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto13.setForeground(new java.awt.Color(0, 0, 0));
        Punto13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 30, 30));

        Punto14.setEditable(false);
        Punto14.setBackground(new java.awt.Color(56, 56, 56));
        Punto14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Punto14.setForeground(new java.awt.Color(0, 0, 0));
        Punto14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Punto14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Punto14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 30, 30));

        Ronda1.setBackground(new java.awt.Color(56, 56, 56));
        Ronda1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Ronda1.setForeground(new java.awt.Color(255, 255, 255));
        Ronda1.setText("Ronda1");
        Ronda1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ronda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ronda1ActionPerformed(evt);
            }
        });
        getContentPane().add(Ronda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 210, 70));

        SemiFinal.setBackground(new java.awt.Color(56, 56, 56));
        SemiFinal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SemiFinal.setForeground(new java.awt.Color(255, 255, 255));
        SemiFinal.setText("SemiFinal");
        SemiFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SemiFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemiFinalActionPerformed(evt);
            }
        });
        getContentPane().add(SemiFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 210, 70));

        Final.setBackground(new java.awt.Color(56, 56, 56));
        Final.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Final.setForeground(new java.awt.Color(255, 255, 255));
        Final.setText("Final");
        Final.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalActionPerformed(evt);
            }
        });
        getContentPane().add(Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 210, 70));

        Reset1.setBackground(new java.awt.Color(56, 56, 56));
        Reset1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Reset1.setForeground(new java.awt.Color(255, 255, 255));
        Reset1.setText("Otro");
        Reset1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(Reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 100, 70));

        Reset.setBackground(new java.awt.Color(56, 56, 56));
        Reset.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Nuevo");
        Reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 110, 70));

        LabelWallpaper.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ronda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ronda1ActionPerformed
        String Error = "Se encontraron caracteres no validos";
        try {
            if (Integer.parseInt(Punto1.getText()) > Integer.parseInt(Punto2.getText())) {
                Nombre9.setText(Nombre1.getText());
                Nombre1.setBackground(win);
                Nombre2.setBackground(lose);
            } else if (Integer.parseInt(Punto1.getText()) == Integer.parseInt(Punto2.getText())) {
                Error = "Se Encontro un empate";
                throw new NullPointerException("Hay empate en: " + Nombre1.getText() + " vs " + Nombre2.getText());
            } else {
                Nombre9.setText(Nombre2.getText());
                Nombre2.setBackground(win);
                Nombre1.setBackground(lose);
            }

            if (Integer.parseInt(Punto3.getText()) > Integer.parseInt(Punto4.getText())) {
                Nombre10.setText(Nombre3.getText());
                Nombre3.setBackground(win);
                Nombre4.setBackground(lose);
            } else if (Integer.parseInt(Punto3.getText()) == Integer.parseInt(Punto4.getText())) {
                Error = "Se Encontro un empate";
                throw new NullPointerException("Hay empate en: " + Nombre3.getText() + " vs " + Nombre4.getText());
            } else {
                Nombre10.setText(Nombre4.getText());
                Nombre4.setBackground(win);
                Nombre3.setBackground(lose);
            }

            if (Integer.parseInt(Punto5.getText()) > Integer.parseInt(Punto6.getText())) {
                Nombre11.setText(Nombre5.getText());
                Nombre5.setBackground(win);
                Nombre6.setBackground(lose);
            } else if (Integer.parseInt(Punto5.getText()) == Integer.parseInt(Punto6.getText())) {
                Error = "Se Encontro un empate";
                throw new NullPointerException("Hay empate en: " + Nombre5.getText() + " vs " + Nombre6.getText());
            } else {
                Nombre11.setText(Nombre6.getText());
                Nombre6.setBackground(win);
                Nombre5.setBackground(lose);
            }

            if (Integer.parseInt(Punto7.getText()) > Integer.parseInt(Punto8.getText())) {
                Nombre12.setText(Nombre7.getText());
                Nombre7.setBackground(win);
                Nombre8.setBackground(lose);
            } else if (Integer.parseInt(Punto7.getText()) == Integer.parseInt(Punto8.getText()) && !Nombre8.getText().equals("(no hay 8)")) {
                Error = "Se Encontro un empate";
                throw new NullPointerException("Hay empate en: " + Nombre7.getText() + " vs " + Nombre8.getText());
            } else {
                Nombre12.setText(Nombre8.getText());
                Nombre8.setBackground(win);
                Nombre7.setBackground(lose);
            }
            if (Nombre8.getText().equals("(no hay 8)")) {
                Nombre12.setText(Nombre7.getText());
                Nombre7.setBackground(negro);
                Nombre8.setBackground(negro);
            }

            Punto1.setBackground(negro);
            Punto2.setBackground(negro);
            Punto3.setBackground(negro);
            Punto4.setBackground(negro);
            Punto5.setBackground(negro);
            Punto6.setBackground(negro);
            Punto7.setBackground(negro);
            Punto8.setBackground(negro);
            Punto1.setForeground(blanco);
            Punto2.setForeground(blanco);
            Punto3.setForeground(blanco);
            Punto4.setForeground(blanco);
            Punto5.setForeground(blanco);
            Punto6.setForeground(blanco);
            Punto7.setForeground(blanco);
            Punto8.setForeground(blanco);

            Nombre9.setBackground(blanco);
            Nombre10.setBackground(blanco);
            Nombre11.setBackground(blanco);
            Nombre12.setBackground(blanco);
            Punto9.setBackground(blanco);
            Punto10.setBackground(blanco);
            Punto11.setBackground(blanco);
            Punto12.setBackground(blanco);

            Ronda1.setVisible(false);
            SemiFinal.setVisible(true);
            Punto1.setEditable(false);
            Punto2.setEditable(false);
            Punto3.setEditable(false);
            Punto4.setEditable(false);
            Punto5.setEditable(false);
            Punto6.setEditable(false);
            Punto7.setEditable(false);
            Punto8.setEditable(false);
            Punto9.setEditable(true);
            Punto10.setEditable(true);
            Punto11.setEditable(true);
            Punto12.setEditable(true);
        } catch (Exception e) {
            Nombre9.setText("");
            Nombre10.setText("");
            Nombre11.setText("");
            Nombre12.setText("");
            JOptionPane.showMessageDialog(this, Error + ".\n (" + e + ")");
        }
    }//GEN-LAST:event_Ronda1ActionPerformed

    private void SemiFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemiFinalActionPerformed
        try {
            if (Integer.parseInt(Punto9.getText()) > Integer.parseInt(Punto10.getText())) {
                Nombre13.setText(Nombre9.getText());
                Nombre9.setBackground(win);
                Nombre10.setBackground(lose);
            } else {
                Nombre13.setText(Nombre10.getText());
                Nombre10.setBackground(win);
                Nombre9.setBackground(lose);
            }

            if (Integer.parseInt(Punto11.getText()) > Integer.parseInt(Punto12.getText())) {
                Nombre14.setText(Nombre11.getText());
                Nombre11.setBackground(win);
                Nombre12.setBackground(lose);
            } else {
                Nombre14.setText(Nombre12.getText());
                Nombre12.setBackground(win);
                Nombre11.setBackground(lose);
            }

            Punto9.setBackground(negro);
            Punto10.setBackground(negro);
            Punto11.setBackground(negro);
            Punto12.setBackground(negro);
            Punto9.setForeground(blanco);
            Punto10.setForeground(blanco);
            Punto11.setForeground(blanco);
            Punto12.setForeground(blanco);

            Nombre13.setBackground(blanco);
            Nombre14.setBackground(blanco);
            Punto13.setBackground(blanco);
            Punto14.setBackground(blanco);

            SemiFinal.setVisible(false);
            Final.setVisible(true);
            Punto9.setEditable(false);
            Punto10.setEditable(false);
            Punto11.setEditable(false);
            Punto12.setEditable(false);
            Punto13.setEditable(true);
            Punto14.setEditable(true);
        } catch (Exception e) {
            Nombre13.setText("");
            Nombre14.setText("");
            JOptionPane.showMessageDialog(this, "Hay caracteres no validos.\n Error(" + e + ")");
        }
    }//GEN-LAST:event_SemiFinalActionPerformed

    private void FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalActionPerformed
        try {
            if (Integer.parseInt(Punto13.getText()) > Integer.parseInt(Punto14.getText())) {
                Ganador.setText(Nombre13.getText());
            } else {
                Ganador.setText(Nombre14.getText());
            }

            Punto13.setBackground(negro);
            Punto14.setBackground(negro);
            Punto13.setForeground(blanco);
            Punto14.setForeground(blanco);

            Final.setVisible(false);
            Punto13.setEditable(false);
            Punto14.setEditable(false);
        } catch (Exception e) {
            Ganador.setText("");
            JOptionPane.showMessageDialog(this, "Hay caracteres no validos.\n Error(" + e + ")");
        }
    }//GEN-LAST:event_FinalActionPerformed

    private void Reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset1ActionPerformed
        new EnArbol8().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Reset1ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ResetActionPerformed

    private void cargarParticipantes() {
        int x = 1;
        List<Participante> data = Participantes.getParticipantes();
        for (Participante p : data) {
            participantes.addRow(new Object[]{p.getNombre()});
        }
        Collections.shuffle(data);

        for (Participante p : data) {
            switch (x) {
                case 1 ->
                    Nombre1.setText(p.getNombre());
                case 2 ->
                    Nombre2.setText(p.getNombre());
                case 3 ->
                    Nombre3.setText(p.getNombre());
                case 4 ->
                    Nombre4.setText(p.getNombre());
                case 5 ->
                    Nombre5.setText(p.getNombre());
                case 6 ->
                    Nombre6.setText(p.getNombre());
                case 7 ->
                    Nombre7.setText(p.getNombre());
                case 8 ->
                    Nombre8.setText(p.getNombre());
                default -> {
                }
            }
            x++;
        }
        if (Nombre8.getText().isEmpty()) {
            Nombre8.setText("(no hay 8)");
            Punto7.setEditable(false);
            Punto8.setEditable(false);
            Punto7.setText("0");
            Punto8.setText("0");
            Nombre7.setBackground(negro);
            Nombre8.setBackground(negro);
            Nombre7.setForeground(blanco);
            Nombre8.setForeground(blanco);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnArbol8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnArbol8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnArbol8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnArbol8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnArbol8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Final;
    private javax.swing.JTextField Ganador;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JTextField Nombre10;
    private javax.swing.JTextField Nombre11;
    private javax.swing.JTextField Nombre12;
    private javax.swing.JTextField Nombre13;
    private javax.swing.JTextField Nombre14;
    private javax.swing.JTextField Nombre2;
    private javax.swing.JTextField Nombre3;
    private javax.swing.JTextField Nombre4;
    private javax.swing.JTextField Nombre5;
    private javax.swing.JTextField Nombre6;
    private javax.swing.JTextField Nombre7;
    private javax.swing.JTextField Nombre8;
    private javax.swing.JTextField Nombre9;
    private javax.swing.JTextField Punto1;
    private javax.swing.JTextField Punto10;
    private javax.swing.JTextField Punto11;
    private javax.swing.JTextField Punto12;
    private javax.swing.JTextField Punto13;
    private javax.swing.JTextField Punto14;
    private javax.swing.JTextField Punto2;
    private javax.swing.JTextField Punto3;
    private javax.swing.JTextField Punto4;
    private javax.swing.JTextField Punto5;
    private javax.swing.JTextField Punto6;
    private javax.swing.JTextField Punto7;
    private javax.swing.JTextField Punto8;
    private javax.swing.JTextField Punto9;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Reset1;
    private javax.swing.JButton Ronda1;
    private javax.swing.JButton SemiFinal;
    private javax.swing.JTable TableParticipantes;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
