/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.Participante;
import clases.Participantes;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MINEDUCYT
 */
public class Participantes8 extends javax.swing.JFrame {

    DefaultTableModel participantes;

    public Participantes8() {
        initComponents();
        this.setLocationRelativeTo(null);

        participantes = new DefaultTableModel();
        participantes.addColumn("ID / Participante");
        TableParticipantes.setModel(participantes);

        cargarParticipantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TableParticipantes = new javax.swing.JTable();
        Punto1 = new javax.swing.JTextField();
        Punto2 = new javax.swing.JTextField();
        Punto3 = new javax.swing.JTextField();
        Punto4 = new javax.swing.JTextField();
        Punto5 = new javax.swing.JTextField();
        Punto6 = new javax.swing.JTextField();
        Punto7 = new javax.swing.JTextField();
        Punto8 = new javax.swing.JTextField();
        Punto9 = new javax.swing.JTextField();
        Punto10 = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JTextField();
        Nombre1 = new javax.swing.JTextField();
        Nombre3 = new javax.swing.JTextField();
        Nombre4 = new javax.swing.JTextField();
        Nombre5 = new javax.swing.JTextField();
        Nombre6 = new javax.swing.JTextField();
        Nombre7 = new javax.swing.JTextField();
        Nombre8 = new javax.swing.JTextField();
        Nombre9 = new javax.swing.JTextField();
        Nombre10 = new javax.swing.JTextField();
        Ganador = new javax.swing.JTextField();
        Ronda1 = new javax.swing.JButton();
        Ronda2 = new javax.swing.JButton();
        Ronda3 = new javax.swing.JButton();
        Punto11 = new javax.swing.JTextField();
        Punto12 = new javax.swing.JTextField();
        Nombre11 = new javax.swing.JTextField();
        Nombre12 = new javax.swing.JTextField();
        Nombre14 = new javax.swing.JTextField();
        Nombre13 = new javax.swing.JTextField();
        Punto13 = new javax.swing.JTextField();
        Punto14 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TableParticipantes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 170));
        getContentPane().add(Punto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 40, 30));
        getContentPane().add(Punto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 40, 30));
        getContentPane().add(Punto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 40, 30));
        getContentPane().add(Punto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 40, 30));
        getContentPane().add(Punto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 40, 30));
        getContentPane().add(Punto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 40, 30));
        getContentPane().add(Punto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 40, 30));
        getContentPane().add(Punto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 40, 30));
        getContentPane().add(Punto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 40, 30));
        getContentPane().add(Punto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 40, 30));
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, 30));
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 90, 30));
        getContentPane().add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 90, 30));
        getContentPane().add(Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 90, 30));
        getContentPane().add(Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 90, 30));
        getContentPane().add(Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 90, 30));
        getContentPane().add(Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 90, 30));
        getContentPane().add(Nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 90, 30));
        getContentPane().add(Nombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, 30));
        getContentPane().add(Nombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 90, 30));
        getContentPane().add(Ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 210, 60));

        Ronda1.setText("Ronda1");
        Ronda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ronda1ActionPerformed(evt);
            }
        });
        getContentPane().add(Ronda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 110, 40));

        Ronda2.setText("SemiFinal");
        Ronda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ronda2ActionPerformed(evt);
            }
        });
        getContentPane().add(Ronda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 120, 40));

        Ronda3.setText("Final");
        Ronda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ronda3ActionPerformed(evt);
            }
        });
        getContentPane().add(Ronda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 120, 40));
        getContentPane().add(Punto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 40, 30));
        getContentPane().add(Punto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 40, 30));
        getContentPane().add(Nombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 90, 30));
        getContentPane().add(Nombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 90, 30));
        getContentPane().add(Nombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 90, 30));
        getContentPane().add(Nombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 90, 30));
        getContentPane().add(Punto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 40, 30));
        getContentPane().add(Punto14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ronda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ronda1ActionPerformed
        try {
            if (Integer.parseInt(Punto1.getText()) > Integer.parseInt(Punto2.getText())) {
                Nombre9.setText(Nombre1.getText());
            } else {
                Nombre9.setText(Nombre2.getText());
            }

            if (Integer.parseInt(Punto3.getText()) > Integer.parseInt(Punto4.getText())) {
                Nombre10.setText(Nombre3.getText());
            } else {
                Nombre10.setText(Nombre4.getText());
            }

            if (Integer.parseInt(Punto5.getText()) > Integer.parseInt(Punto6.getText())) {
                Nombre11.setText(Nombre5.getText());
            } else {
                Nombre11.setText(Nombre6.getText());
            }

            if (Integer.parseInt(Punto7.getText()) > Integer.parseInt(Punto8.getText())) {
                Nombre12.setText(Nombre7.getText());
            } else {
                Nombre12.setText(Nombre8.getText());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Hay espacios en blanco\n Error(" + e + ")");
        }
    }//GEN-LAST:event_Ronda1ActionPerformed

    private void Ronda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ronda2ActionPerformed
        try {
            if (Integer.parseInt(Punto9.getText()) > Integer.parseInt(Punto10.getText())) {
                Nombre13.setText(Nombre9.getText());
            } else {
                Nombre13.setText(Nombre10.getText());
            }

            if (Integer.parseInt(Punto11.getText()) > Integer.parseInt(Punto12.getText())) {
                Nombre14.setText(Nombre11.getText());
            } else {
                Nombre14.setText(Nombre12.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Hay espacios en blanco\n Error(" + e + ")");
        }
    }//GEN-LAST:event_Ronda2ActionPerformed

    private void Ronda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ronda3ActionPerformed
        try {
            if (Integer.parseInt(Punto13.getText()) > Integer.parseInt(Punto14.getText())) {
                Ganador.setText(Nombre13.getText());
            } else {
                Ganador.setText(Nombre14.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Hay espacios en blanco\n Error(" + e + ")");
        }
    }//GEN-LAST:event_Ronda3ActionPerformed

    private void cargarParticipantes() {
        int x = 1;
        List<Participante> data = Participantes.getParticipantes();
        for (Participante p : data) {
            participantes.addRow(new Object[]{p.getId() + " - " + p.getNombre()});
        }
        Collections.shuffle(data);

        for (Participante p : data) {
            switch (x) {
                case 1 ->
                    Nombre1.setText(p.getNombre());
                case 2 ->
                    Nombre2.setText(p.getNombre());
                case 3 ->
                    Nombre3.setText(p.getNombre());
                case 4 ->
                    Nombre4.setText(p.getNombre());
                case 5 ->
                    Nombre5.setText(p.getNombre());
                case 6 ->
                    Nombre6.setText(p.getNombre());
                case 7 ->
                    Nombre7.setText(p.getNombre());
                case 8 ->
                    Nombre8.setText(p.getNombre());
                default -> {
                }
            }
            x++;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Participantes8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Participantes8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Participantes8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Participantes8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Participantes8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ganador;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JTextField Nombre10;
    private javax.swing.JTextField Nombre11;
    private javax.swing.JTextField Nombre12;
    private javax.swing.JTextField Nombre13;
    private javax.swing.JTextField Nombre14;
    private javax.swing.JTextField Nombre2;
    private javax.swing.JTextField Nombre3;
    private javax.swing.JTextField Nombre4;
    private javax.swing.JTextField Nombre5;
    private javax.swing.JTextField Nombre6;
    private javax.swing.JTextField Nombre7;
    private javax.swing.JTextField Nombre8;
    private javax.swing.JTextField Nombre9;
    private javax.swing.JTextField Punto1;
    private javax.swing.JTextField Punto10;
    private javax.swing.JTextField Punto11;
    private javax.swing.JTextField Punto12;
    private javax.swing.JTextField Punto13;
    private javax.swing.JTextField Punto14;
    private javax.swing.JTextField Punto2;
    private javax.swing.JTextField Punto3;
    private javax.swing.JTextField Punto4;
    private javax.swing.JTextField Punto5;
    private javax.swing.JTextField Punto6;
    private javax.swing.JTextField Punto7;
    private javax.swing.JTextField Punto8;
    private javax.swing.JTextField Punto9;
    private javax.swing.JButton Ronda1;
    private javax.swing.JButton Ronda2;
    private javax.swing.JButton Ronda3;
    private javax.swing.JTable TableParticipantes;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
